---
- name: Install Apache
  hosts: aws

  tasks: 
    - name: Install apache. 
      command: yum install --quiet -y httpd httpd-devel
    - name: Copy configuration files.
      command: >
        cp httpd.conf /etc/httpd/conf/httpd.conf
      command: >
        cp httpd-vhosts /etc/httpd/conf/httpd-vhosts.conf
    - name: Start apache and configure it to run on boot.
      command: service httpd start
      command: chkconfig httpd on




      - name: Install apache. 
        yum:
          name: 
            - httpd
            - httpd-devel
            state: present
       - name: Copy configuration files.
        copy: 
          src: "{{ item['src'] }}" #jenja 
          dest: "{{ item['dest'] }}"
          owner: root
          group: root
          mode: 0644
        with_items: 
          - src: httpd.config
            dest: /etc/httpd/conf/httpd.conf
          - src: httpd-vhosts.conf
            dest: /etc/httpd/conf/httpd-vhosts.conf
        - name: Ensure apache is started and configure it to run at boot.
          service: 
            name: httpd
            state: started
            enabled: yes






---
- name: Install apache.
  hosts: all

  tasks: Install apache.
  shell: |
    yum install --quiet -y httpd httpd-devel
    cp httpd.conf /etc/httpd/conf/httpd.configure
    cp httpd-vhosts /etc/htppd/conf/httpd-vhosts.conf